using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class catatuy : MonoBehaviour
{
    // Start is called before the first frame update
    void Start()
    {
        //MERABA MERABAMERABA MERABAMERABA MERABAMERABA MERABAMERABA MERABAMERABA MERABAMERABA MERABAMERABA MERABAMERABA MERABAMERABA MERABA
        //MERABA MERABA
        //MERABA MERABA
        //MERABA MERABA
        //MERABA MERABA
        //MERABA MERABA//MERABA MERABAMERABA MERABAMERABA MERABAMERABA MERABAMERABA MERABAMERABA MERABAMERABA MERABAMERABA MERABAMERABA MERABAMERABA MERABA
        //MERABA MERABA
        //MERABA MERABA
        //MERABA MERABA
        //MERABA MERABA
        //MERABA MERABA//MERABA MERABAMERABA MERABAMERABA MERABAMERABA MERABAMERABA MERABAMERABA MERABAMERABA MERABAMERABA MERABAMERABA MERABAMERABA MERABA
        //MERABA MERABA
        //MERABA MERABA
        //MERABA MERABA
        //MERABA MERABA
        //MERABA MERABA
    }

    // Update is called once per frame
    void Update()
    {
        
    }
}
